name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run tests
      run: go test ./...

    - name: Build binaries
      run: |
        # Linux
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o spacecrafts-fiber-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o spacecrafts-fiber-linux-arm64 .
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o spacecrafts-fiber-windows-amd64.exe .
        
        # macOS
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o spacecrafts-fiber-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o spacecrafts-fiber-darwin-arm64 .

    - name: Create checksums
      run: |
        sha256sum spacecrafts-fiber-* > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          spacecrafts-fiber-*
          checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
